name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Node.js environment
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Copy `.env` file
      run: cp ./env-files/.env.${process.env.TEST_ENV } .env # Replace with your actual `.env` file path
      
      #dotenv.config({ path: `./env-files/.env.${process.env.TEST_ENV}` });


    # Step 3: Install dependencies using npm ci
    - name: Install dependencies
      run: npm ci

    # Step 4: Install Playwright Browsers without force flag
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Step 5: Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test

    # Step 6: Upload Playwright test report as an artifact
    - uses: actions/upload-artifact@v4
      if: ${{ always() }}  # Upload the artifact even if the tests fail
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
